language: php

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

sudo: required
dist: trusty

services:
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
  - php: 5.6
    env: BRANCH=1.6.1.x

before_script:
  - bash tests/bin/clone_prestashop.sh
  - bash tests/bin/setup_apache.sh
  - bash tests/bin/before_script.sh

script:
  - bash tests/bin/script.sh

deploy:
  skip_cleanup: true
  provider: script
  script: make
  on:
    php: 7.2
    branch: master
    condition: "$DEPLOY = true"
